# Generated by Django 5.0.7 on 2024-07-30 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_sage_meta", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CommentPublisher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("caption", models.TextField(max_length=255)),
                (
                    "media",
                    models.ForeignKey(
                        help_text="Which media is for this comment",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_comment",
                        to="django_sage_meta.media",
                        verbose_name="media_comment",
                    ),
                ),
                (
                    "replay",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_sage_meta.commentpublisher",
                        verbose_name="replay",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comment_Publish",
                "verbose_name_plural": "Comment_Publishs",
            },
        ),
        migrations.CreateModel(
            name="PostPublisher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_url", models.CharField(max_length=255)),
                ("caption", models.TextField(max_length=255)),
                (
                    "kind",
                    models.CharField(
                        choices=[("reels", "REELS"), ("post", "POST")],
                        max_length=10,
                        verbose_name="kind",
                    ),
                ),
                ("carousel", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "post_publisher",
                "verbose_name_plural": "post_publishers",
            },
        ),
        migrations.CreateModel(
            name="StoryPublisher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_url", models.CharField(max_length=255)),
                ("caption", models.TextField(max_length=255)),
                (
                    "kind",
                    models.CharField(
                        choices=[("reels", "REELS"), ("post", "POST")],
                        max_length=10,
                        verbose_name="kind",
                    ),
                ),
                ("carousel", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "story_publisher",
                "verbose_name_plural": "story_publishers",
            },
        ),
    ]
