# Generated by Django 5.0.7 on 2024-07-30 14:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("django_sage_meta", "0002_commentpublisher_postpublisher_storypublisher"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="storypublisher",
            name="caption",
        ),
        migrations.RemoveField(
            model_name="storypublisher",
            name="carousel",
        ),
    ]
