# Generated by Django 5.0.7 on 2024-07-30 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_sage_meta", "0003_remove_storypublisher_caption_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commentpublisher",
            name="caption",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="postpublisher",
            name="caption",
            field=models.TextField(),
        ),
    ]
