# Generated by Django 5.0.7 on 2024-07-30 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_sage_meta", "0004_alter_commentpublisher_caption_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postpublisher",
            name="file_url",
            field=models.TextField(),
        ),
    ]
